In MXNet scalars are NDArrays with just one element

In [1]:
from mxnet import nd

In [2]:
x = nd.array([3.0])
y = nd.array([2.0])

print('x + y = ', x + y)
print('x - y = ', x - y)
print('x * y = ', x * y)
print('x / y = ', x / y)
print('x ** y = ', nd.power(x, y))

x + y =  
[5.]
<NDArray 1 @cpu(0)>
x - y =  
[1.]
<NDArray 1 @cpu(0)>
x * y =  
[6.]
<NDArray 1 @cpu(0)>
x / y =  
[1.5]
<NDArray 1 @cpu(0)>
x ** y =  
[9.]
<NDArray 1 @cpu(0)>


We can convert any NDArray to a Python float by calling its asscalar method.
Note that this is typically a bad idea. 
While doing this, NDArray has to stop doing anything else 
in order to hand the result and process control back to Python.

In [3]:
print(x)
print(x.asscalar())


[3.]
<NDArray 1 @cpu(0)>
3.0


Vectors are e.g. [1.0, 3.0, 4.0, 2.0]. We use 1D NDArrays

In [4]:
x = nd.arange(5)
print('x = ', x)
print(x[3])

x =  
[0. 1. 2. 3. 4.]
<NDArray 5 @cpu(0)>

[3.]
<NDArray 1 @cpu(0)>


The length of a vector is commonly called its dimension.
As with an ordinary Python array, we can access the length of an NDArray by calling Python's in-built len() function
We can also access a vector's length via its .shape attribute.
The shape is a tuple that lists the dimensionality along each of its axes.

In [5]:
x.shape

(5,)

The word dimension is overloaded between number of axes and number of elements.
To avoid confusion, when say 2D array or 3D array, we mean an array with 2 or 3 axes respectively.
But if we say n-dimensional vector, we mean a vector of length n.

In [6]:
a = 2
x = nd.array([1, 2, 3])
y = nd.array([10, 20, 30])
print(a * x)
print(a * x + y)


[2. 4. 6.]
<NDArray 3 @cpu(0)>

[12. 24. 36.]
<NDArray 3 @cpu(0)>


In [7]:
print(nd.arange(10))
A = nd.arange(20).reshape((2, 10))
print(A)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<NDArray 10 @cpu(0)>

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
<NDArray 2x10 @cpu(0)>


In [8]:
# transpose the matrix
print(A.T)


[[ 0. 10.]
 [ 1. 11.]
 [ 2. 12.]
 [ 3. 13.]
 [ 4. 14.]
 [ 5. 15.]
 [ 6. 16.]
 [ 7. 17.]
 [ 8. 18.]
 [ 9. 19.]]
<NDArray 10x2 @cpu(0)>


Tensor
Just as vectors generalize saclars, and matrices generalize vectors, we can increase the number of axes.
When working with images the axes correspond to the height, width, and the three (RGB) color channels.

In [9]:
X = nd.arange(24).reshape((2, 3, 4))
print('X.shape = ', X.shape)
print('X = ', X)

X.shape =  (2, 3, 4)
X =  
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
<NDArray 2x3x4 @cpu(0)>


Basic properties of tensor arithmetic
Given two tensors X and Y with the same shape, aX + Y has the same shape

In [10]:
a = 2
x = nd.ones(3)
y = nd.zeros(3)
print(x.shape)
print(y.shape)
print((a * x).shape)
print((a * x + y).shape)

(3,)
(3,)
(3,)
(3,)


In [11]:
x = nd.arange(12)
x = x.reshape((3, 4))
print(x)
print(nd.sum(x))
print(nd.sum(x, 0))
print(nd.sum(x, 1))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[66.]
<NDArray 1 @cpu(0)>

[12. 15. 18. 21.]
<NDArray 4 @cpu(0)>

[ 6. 22. 38.]
<NDArray 3 @cpu(0)>


In [12]:
print(nd.mean(A))
print(nd.sum(A) / A.size)


[9.5]
<NDArray 1 @cpu(0)>

[9.5]
<NDArray 1 @cpu(0)>


In [13]:
# Dot products
x = nd.arange(4) + 1.0
y = nd.ones(4)
print(x, y, nd.dot(x, y))


[1. 2. 3. 4.]
<NDArray 4 @cpu(0)> 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)> 
[10.]
<NDArray 1 @cpu(0)>


In [14]:
# we can express the dot product of two vectors nd.dot(u, v) equivalently by performing element-wise multiplication and then a sum
nd.sum(x * y)


[10.]
<NDArray 1 @cpu(0)>

We can also use matrix-vector products to describe the calculations of each layer in a neural network
Expressing matrix-vector products in code with ndarray, use the same nd.dot() function as for dot products

In [15]:
A = A.reshape((3, 4))
# A is a 3x4 matrix, x is a 4-dimensional vector
print(nd.dot(A, x))
print(A * x)


[ 20.  60. 100.]
<NDArray 3 @cpu(0)>

[[ 0.  2.  6. 12.]
 [ 4. 10. 18. 28.]
 [ 8. 18. 30. 44.]]
<NDArray 3x4 @cpu(0)>


In [16]:
# matrix-matrix multiplication
B = nd.ones(shape=(4, 3))  # B is a 4x3 matrix
nd.dot(A, B)


[[ 6.  6.  6.]
 [22. 22. 22.]
 [38. 38. 38.]]
<NDArray 3x3 @cpu(0)>

In [17]:
# to calculate the l2 norm, we can just call nd.norm()
nd.norm(x)


[5.477226]
<NDArray 1 @cpu(0)>

In [18]:
# to calculate the l1-norm we can simply perform the absolute value and then sum over the elements
nd.sum(nd.abs(x))


[10.]
<NDArray 1 @cpu(0)>